### ISSUE TITLE
Wordpress plugin not working

### ISSUE THREAD

**Issue by ACPK** [techies23/video-conference-zoom#1]
The screens are blank after entering the API credentials.

**Comment by techies23** [comment]
Hello ACPK,

Please refer this https://drive.google.com/file/d/0Bw_pLxEfyUXWYVEyOFZZOFBtaHc/view. To properly install the plugin. Please install the plugin from WordPress repo for latest releases. If following the tutorial from above link also does not work then contact me again. Thank you.

**Comment by ACPK** [comment]
@techies23 - Done and done (up the API key part). The admin page for the plugin that isn't blank when activated is the settings page. The API settings are correct as I'm able to curl to Zoom's endpoint.

**Comment by techies23** [comment]
Can you turn on the debug and send the screenshot ? Thanx..
