### ISSUE TITLE
API connection check

### ISSUE THREAD

**Issue by techies23** [techies23/video-conference-zoom#92]
Added more robust API connection check option for users - Allows more clear visibility if all Zoom API keys are correct. Normal server-to-server keys have been validated.

To be solved:
-----------------
- SDK Keys needs to trigger Zoom JS SDK or ? something that needs more research atm.

**Comment by digamber89** [comment]
I've added a way to - verify the credentials in the backend. Please review.

**Comment by digamber89** [comment]
Accidentally closed

**Comment by techies23** [comment]
Verify last changes

**Comment by digamber89** [comment]
@techies23 may be consider adding a back button on S2S Oauth screen
![Screenshot 2023-09-04 at 18 00 28](https://github.com/techies23/video-conference-zoom/assets/6367450/a9e464c3-421b-46ea-a0f0-304464e4be7a)

**Comment by digamber89** [comment]
@techies23 when are we launching this ?
